# Generated by Django 3.1.7 on 2021-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Ptype',
            field=models.CharField(choices=[('software', 'SOFTWARE'), ('web', 'WEB'), ('application', 'APPLICATION'), ('marketing', 'MARKETING'), ('other', 'OTHER')], default='other', max_length=15),
        ),
    ]
