# Generated by Django 3.1.7 on 2021-04-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccounts_atype'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='username',
            field=models.CharField(default='nobe', max_length=12),
        ),
    ]
